### ISSUE TITLE
52上看到，特来膜拜大神

### ISSUE THREAD

**Issue by BackT0TheFuture** [wwh1004/blog#1]
非托管混淆工具对高手来说只是个纸老虎，但对于很多人还是有点用的，
INTELLILOCK 和 Reactor都已有新版本，大神有空能不能跟进下！

**Comment by wwh1004** [comment]
有时间再看看吧。我之前发了破解.NET Reactor的教程，新版应该也是一样破解。你可以自己试试，应该不是太难的。

**Comment by BackT0TheFuture** [comment]
谢谢，正在学习中
