### ISSUE TITLE
Any plans on making English posts?

### ISSUE THREAD

**Issue by zsr2531** [wwh1004/blog#3]
Your posts seem like they contain good information, but there are a lot of non-chinese people like me who sadly can't read it and rely on only screenshots...

It would be nice if you could provide English versions for some posts.

**Comment by wwh1004** [comment]
I am not goot at English. And now I have other things to do so I do not have time to work on .NET reverse engineering. As you see, the last time that I post blog is “4 months ago”. So I feel sorry for that.
